/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import clase31.SQLError;
import clase31.tablas.UsuarioTablaModelo;
import dao.DepartamentoDao;
import dao.ProvinciaDao;
import dao.UsuarioDao;
import entidades.Departamento;
import entidades.Provincia;
import entidades.Usuario;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author alumno
 */
public class abm extends javax.swing.JFrame {

    /**
     * Creates new form abm
     */
    public abm() {
        initComponents();
        mostrarUsuarios(null);
        rellenarComboProvincia();
        dptoCombo.setEnabled(false);
    }
    
    public void rellenarComboProvincia(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        ProvinciaDao pdao               = new ProvinciaDao();
        LinkedList<Provincia> lista     = pdao.getAll();
                        
        for (Provincia provincia : lista) {
            modelo.addElement(provincia);            
        }
        
        provinciaCombo.setModel(modelo);        
    }
    
    public void rellenarComboDepartamento(int id_provincia){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        DepartamentoDao dptoDao         = new DepartamentoDao();        
        LinkedList<Departamento> lista     = dptoDao.getByProvinciaId(id_provincia);
                        
        for (Departamento dpto : lista) {
            modelo.addElement(dpto);            
        }
        
        dptoCombo.setModel(modelo);        
    }
    
    public void mostrarUsuarios(String valorBuscado){
        UsuarioTablaModelo modelo = new UsuarioTablaModelo();
        
        usuariosTbl.setModel(modelo);
        usuariosTbl.getColumnModel().getColumn(0).setResizable(false);
        usuariosTbl.getColumnModel().getColumn(0).setMinWidth(0);
        usuariosTbl.getColumnModel().getColumn(0).setMaxWidth(0);
        
        LinkedList<Usuario> lista = new LinkedList<Usuario>();
        UsuarioDao udao = new UsuarioDao();
        if(valorBuscado == null){
            lista = udao.getAll();
        } else {
            lista = udao.getByAllFields(valorBuscado);
        }
        
        String[] data = new String[4];
        for (Usuario usuario : lista) {
            data[0] = String.valueOf(usuario.getId());
            data[1] = String.valueOf(usuario.getDni());
            data[2] = usuario.getNombre();
            data[3] = usuario.getApellido();                                
            modelo.addRow(data);
        }
                   
        usuariosTbl.setModel(modelo);            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        menuTabla = new javax.swing.JPopupMenu();
        eliminar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dniTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        apellidoTxt = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();
        dniError = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usuariosTbl = new javax.swing.JTable();
        buscarTxt = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        nuevoBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        provinciaCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        dptoCombo = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        menuTabla.add(eliminar);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        menuTabla.add(Modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        dniError.setForeground(new java.awt.Color(255, 0, 0));

        usuariosTbl.setComponentPopupMenu(menuTabla);
        jScrollPane2.setViewportView(usuariosTbl);

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        nuevoBtn.setText("Nuevo / Limpiar");
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Provincia");

        provinciaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        provinciaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaComboActionPerformed(evt);
            }
        });

        jLabel5.setText("Departamento");

        dptoCombo.setModel(new DefaultComboBoxModel());
        dptoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dptoComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dniTxt)
                            .addComponent(nombreTxt)
                            .addComponent(apellidoTxt)
                            .addComponent(provinciaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dptoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarBtn)
                                .addGap(82, 82, 82)
                                .addComponent(nuevoBtn))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarBtn)))
                .addGap(18, 18, 18)
                .addComponent(dniError, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniError))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(provinciaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dptoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBtn)
                    .addComponent(nuevoBtn)
                    .addComponent(guardarBtn))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        boolean error   = false;
        int dni         = 0;
        
        dniError.setText("");
        
        try {
            dni = Integer.parseInt(dniTxt.getText());
        } catch (Exception e) {
            error = true;
            dniError.setText("El dni debe ser un numero entero.");
        }
        
        if(!error){
            UsuarioDao udao = new UsuarioDao();
            Usuario usuario = new Usuario();
            usuario.setDni(dni);
            usuario.setNombre(nombreTxt.getText());
            usuario.setApellido(apellidoTxt.getText());
            
            if(this.id_modificar == -1){                            
                udao.insert(usuario);
            } else {
                usuario.setId(this.id_modificar);
                udao.update(usuario);
            }
            
            reset();            
            mostrarUsuarios(null);            
        }
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void reset(){
        this.id_modificar = -1;            
        dniTxt.setText("");
        nombreTxt.setText("");
        apellidoTxt.setText("");
        guardarBtn.setText("Guardar");
            
    }
    
    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        String valorBuscado = buscarTxt.getText();
        mostrarUsuarios(valorBuscado);
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int fila = usuariosTbl.getSelectedRow();
            
        if(fila < 0){
            return;
        }
        
        if(JOptionPane.showConfirmDialog(this, "¿Desea borrar a " + usuariosTbl.getValueAt(fila, 2) + " " + usuariosTbl.getValueAt(fila, 3)) != 0){
            return;
        }
        
        int id = Integer.parseInt(usuariosTbl.getValueAt(fila, 0).toString());
           
        Usuario usuario = new Usuario();
        usuario.setId(id);
        
        UsuarioDao udao = new UsuarioDao();
        udao.delete(usuario);
        
        
        mostrarUsuarios(null);
        
               
        
    }//GEN-LAST:event_eliminarActionPerformed

    private int id_modificar = -1;
            
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        int fila = usuariosTbl.getSelectedRow();
            
        if(fila < 0){
            return;        
        }
        
        int id = Integer.parseInt(usuariosTbl.getValueAt(fila, 0).toString());
        
        UsuarioDao udao = new UsuarioDao();
        Usuario usuario = udao.getById(id);
        
        this.id_modificar = usuario.getId();
        dniTxt.setText(String.valueOf(usuario.getDni()));
        nombreTxt.setText(usuario.getNombre());
        apellidoTxt.setText(usuario.getApellido());
        
        guardarBtn.setText("Actualizar");
    }//GEN-LAST:event_ModificarActionPerformed

    private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
        reset();
    }//GEN-LAST:event_nuevoBtnActionPerformed

    private void provinciaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaComboActionPerformed
        dptoCombo.setEnabled(false);
        Provincia provincia = (Provincia)provinciaCombo.getSelectedItem();
        rellenarComboDepartamento(provincia.getId());        
        dptoCombo.setEnabled(true);
    }//GEN-LAST:event_provinciaComboActionPerformed

    private void dptoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dptoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dptoComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(abm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(abm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(abm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(abm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new abm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField buscarTxt;
    private javax.swing.JLabel dniError;
    private javax.swing.JTextField dniTxt;
    private javax.swing.JComboBox<String> dptoCombo;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPopupMenu menuTabla;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JComboBox<String> provinciaCombo;
    private javax.swing.JTable usuariosTbl;
    // End of variables declaration//GEN-END:variables
}
